# Generated by Django 5.2 on 2025-06-02 01:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="correo electronico",
                        max_length=50,
                        unique=True,
                        verbose_name="correo electronico",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificacion"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="usuario activo"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="administrador"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="superusuario"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "USUARIO",
                "verbose_name_plural": "USUARIOS",
                "db_table": "USUARIO",
                "ordering": ["-fecha_creacion"],
                "indexes": [models.Index(fields=["email"], name="email_idx")],
            },
        ),
    ]
